"""comment table2

Revision ID: 10536dbe2920
Revises: cf4904572bd4
Create Date: 2020-12-25 15:59:57.182326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10536dbe2920'
down_revision = 'cf4904572bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postComment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postComment',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'comment_id')
    )
    # ### end Alembic commands ###
