"""cascade

Revision ID: 202cdafd2468
Revises: cf6547072bdc
Create Date: 2020-12-29 13:57:59.516400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202cdafd2468'
down_revision = 'cf6547072bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['postId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('post', 'likeNum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likeNum', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['postId'], ['id'])
    # ### end Alembic commands ###
