"""likes

Revision ID: cf6547072bdc
Revises: 0f66b3acc240
Create Date: 2020-12-27 16:58:03.670967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6547072bdc'
down_revision = '0f66b3acc240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('postId', 'userId')
    )
    op.add_column('post', sa.Column('likeNum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'likeNum')
    op.drop_table('like')
    # ### end Alembic commands ###
